### ISSUE TITLE
npm script build:ts fails

### ISSUE THREAD

**Issue by random82** [ng-cookbook/angular2-redux-complex-ui#1]
I'm not able to go through the build process on build:ts step:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Users\me\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:ts' ]
2 info using npm@3.10.5
3 info using node@v5.1.0
4 verbose run-script [ 'prebuild:ts', 'build:ts', 'postbuild:ts' ]
5 info lifecycle angular2-redux-complex-ui@1.0.0~prebuild:ts: angular2-redux-complex-ui@1.0.0
6 silly lifecycle angular2-redux-complex-ui@1.0.0~prebuild:ts: no script for prebuild:ts, continuing
7 info lifecycle angular2-redux-complex-ui@1.0.0~build:ts: angular2-redux-complex-ui@1.0.0
8 verbose lifecycle angular2-redux-complex-ui@1.0.0~build:ts: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-redux-complex-ui@1.0.0~build:ts: PATH: [removed for brevity]
11 silly lifecycle angular2-redux-complex-ui@1.0.0~build:ts: Args: [ '/d /s /c', 'tsc' ]
12 silly lifecycle angular2-redux-complex-ui@1.0.0~build:ts: Returned: code: 2  signal: null
13 info lifecycle angular2-redux-complex-ui@1.0.0~build:ts: Failed to exec build:ts script
14 verbose stack Error: angular2-redux-complex-ui@1.0.0 build:ts: `tsc`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-redux-complex-ui@1.0.0
16 verbose cwd C:\Users\Me\Source\Repos\angular2-redux-complex-ui
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\Me\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "build:ts"
19 error node v5.1.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error angular2-redux-complex-ui@1.0.0 build:ts: `tsc`
22 error Exit status 2
23 error Failed at the angular2-redux-complex-ui@1.0.0 build:ts script 'tsc'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-redux-complex-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-redux-complex-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-redux-complex-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dfbaskin** [comment]
Not sure.  I just tried it using Node v5.11.1 and NPM v3.8.6 and everything worked fine (I'm on Windows 10).

**Comment by random82** [comment]
I've tried on other machine and it works fine. 
node v4.4.7
npm v3.10.5
I'll try one more time on the first one to see if I can do anything about it.
